use std::collections::{HashMap, HashSet};

use gpui::Keystroke;
use napi::bindgen_prelude::{Error, Result};
use serde::Deserialize;

/// Event emitted when an application command is invoked by a shortcut or menu.
pub(crate) const APPLICATION_COMMAND_EVENT: &str = "applicationCommand";

/// A command sent by the public Solid API.
///
/// `id` is an opaque registration token generated by the Solid layer. Native
/// code intentionally does not assign meaning to it: it only returns it in
/// the event payload so the owning callback can be looked up safely.
#[derive(Clone, Debug, Deserialize)]
pub(crate) struct ApplicationCommand {
    pub id: String,
    pub label: String,
    pub shortcut: Option<String>,
    #[serde(rename = "scopeElementId")]
    pub scope_element_id: Option<u64>,
    #[serde(default, rename = "allowRepeat")]
    pub allow_repeat: bool,
    pub enabled: bool,
    pub menu: Option<String>,
}

/// A validated command plus the parsed GPUI shortcut, when one was provided.
#[derive(Clone, Debug)]
pub(crate) struct ParsedApplicationCommand {
    pub command: ApplicationCommand,
    pub shortcut: Option<Keystroke>,
}

/// Parse and validate the complete command list before it is installed.
///
/// Validation is deliberately performed on the full list so callers can keep
/// the previous list active when a replacement is malformed. GPUI treats
/// `cmd`, `super`, and `win` as the same platform modifier; using the parsed
/// representation makes those aliases collide as expected.
pub(crate) fn parse_application_commands(json: &str) -> Result<Vec<ParsedApplicationCommand>> {
    let commands: Vec<ApplicationCommand> = serde_json::from_str(json).map_err(|error| {
        Error::from_reason(format!("Invalid application commands JSON: {error}"))
    })?;

    let mut ids = HashSet::with_capacity(commands.len());
    let mut shortcuts = HashMap::<(gpui::Modifiers, String), String>::new();
    let mut parsed = Vec::with_capacity(commands.len());

    for command in commands {
        if command.id.trim().is_empty()
            || command.label.trim().is_empty()
            || command
                .menu
                .as_ref()
                .is_some_and(|menu| menu.trim().is_empty())
        {
            return Err(Error::from_reason(
                "Application command id, label, and menu must not be empty",
            ));
        }
        if !ids.insert(command.id.clone()) {
            return Err(Error::from_reason(format!(
                "Duplicate application command id {:?}",
                command.id
            )));
        }

        let shortcut = command
            .shortcut
            .as_deref()
            .map(parse_application_shortcut)
            .transpose()?;
        if let Some(shortcut) = &shortcut {
            let key = (shortcut.modifiers, shortcut.key.clone());
            if let Some(previous_id) = shortcuts.insert(key, command.id.clone()) {
                return Err(Error::from_reason(format!(
                    "Application command {:?} shortcut {:?} is already registered by {:?}",
                    command.id,
                    command.shortcut.as_deref().unwrap_or_default(),
                    previous_id
                )));
            }
        }

        parsed.push(ParsedApplicationCommand { command, shortcut });
    }

    Ok(parsed)
}

fn parse_application_shortcut(source: &str) -> Result<Keystroke> {
    if source.split_whitespace().count() != 1 {
        return Err(Error::from_reason(format!(
            "Application command shortcut {:?} must be a single chord",
            source
        )));
    }

    let normalized = source
        .split('-')
        .map(|part| {
            if part.eq_ignore_ascii_case("option") {
                "alt"
            } else {
                part
            }
        })
        .collect::<Vec<_>>()
        .join("-");
    let keystroke = Keystroke::parse(&normalized).map_err(|error| {
        Error::from_reason(format!(
            "Invalid application command shortcut {source:?}: {error}"
        ))
    })?;
    if keystroke.modifiers.function {
        return Err(Error::from_reason(format!(
            "Application command shortcut {source:?} must not use fn"
        )));
    }
    if keystroke.key == "tab" {
        return Err(Error::from_reason(
            "Application command shortcut must not use tab",
        ));
    }
    if keystroke.key.is_empty()
        || matches!(
            keystroke.key.as_str(),
            "shift" | "control" | "alt" | "platform" | "function"
        )
    {
        return Err(Error::from_reason(
            "Application command shortcut requires a non-modifier key",
        ));
    }

    Ok(keystroke)
}

#[derive(Clone, PartialEq, gpui::Action)]
#[action(namespace = solo_commands, no_json)]
struct InvokeCommand {
    id: String,
}

gpui::actions!(solo_commands, [Quit]);

struct CommandState {
    commands: Vec<ParsedApplicationCommand>,
    callback: Option<crate::renderer::EventCallback>,
    base_menus: Vec<gpui::OwnedMenu>,
}

impl gpui::Global for CommandState {}

pub(crate) fn has_commands(cx: &gpui::App) -> bool {
    cx.try_global::<CommandState>()
        .is_some_and(|state| !state.commands.is_empty())
}

/// Scope is keyboard-only: explicit native menu selection still uses enabled.
fn accepts_focus(
    command: &ParsedApplicationCommand,
    focused: Option<u64>,
    tree: &crate::retained_tree::RetainedTree,
) -> bool {
    let Some(key) = &command.shortcut else {
        return false;
    };
    let guarded = command.command.scope_element_id.is_some() || !key.modifiers.platform;
    if !guarded {
        return true;
    }
    let mut current = focused;
    let mut in_scope = command.command.scope_element_id.is_none();
    while let Some(id) = current {
        let Some(element) = tree.elements.get(&id) else {
            return false;
        };
        if matches!(
            element.element_type.as_str(),
            "input" | "textarea" | "webview"
        ) {
            return false;
        }
        // Let focused controls handle activation, even inside an article scope.
        if Some(id) == focused
            && matches!(key.key.as_str(), "space" | "enter")
            && !key.modifiers.platform
            && !key.modifiers.control
            && !key.modifiers.alt
            && (element.events.contains("click")
                || element.custom_props.get("role").and_then(|v| v.as_str()) == Some("button"))
        {
            return false;
        }
        in_scope |= command.command.scope_element_id == Some(id);
        if tree.root_id == Some(id) {
            return in_scope;
        }
        current = element.parent;
    }
    false
}

pub(crate) fn dispatch_shortcut(
    event: &gpui::KeyDownEvent,
    view: &crate::renderer::SoloView,
    window: &mut gpui::Window,
    cx: &mut gpui::App,
) {
    let Some(state) = cx.try_global::<CommandState>() else {
        return;
    };
    let focused = view
        .focus_handles
        .iter()
        .find_map(|(id, handle)| handle.is_focused(window).then_some(*id));
    let tree = view.tree.lock().unwrap();
    let Some(entry) = state.commands.iter().find(|entry| {
        entry.command.enabled
            && entry.shortcut.as_ref().is_some_and(|key| {
                key.modifiers == event.keystroke.modifiers && key.key == event.keystroke.key
            })
            && accepts_focus(entry, focused, &tree)
    }) else {
        return;
    };
    if (entry.command.scope_element_id.is_some() || !event.keystroke.modifiers.platform)
        && native_child_has_focus(window)
    {
        return;
    }
    if event.prefer_character_input {
        return;
    }
    if !event.is_held || entry.command.allow_repeat {
        crate::renderer::emit_event_full(&state.callback, 0, APPLICATION_COMMAND_EVENT, |event| {
            event.value = Some(entry.command.id.clone());
        });
    }
    // Swallow repeats too, so holding a toggle cannot leak to a local handler.
    cx.stop_propagation();
}

#[cfg(target_os = "macos")]
pub(crate) fn native_child_has_focus(window: &gpui::Window) -> bool {
    use raw_window_handle::{HasWindowHandle, RawWindowHandle};
    let Ok(handle) = HasWindowHandle::window_handle(window) else {
        return false;
    };
    let RawWindowHandle::AppKit(handle) = handle.as_raw() else {
        return false;
    };
    // SAFETY: the live GPUI window owns this view throughout this UI-thread call.
    let view = unsafe { &*handle.ns_view.as_ptr().cast::<objc2_app_kit::NSView>() };
    view.window()
        .and_then(|window| window.firstResponder())
        .is_some_and(|responder| {
            let responder: *const objc2_app_kit::NSResponder = &*responder;
            responder.cast::<std::ffi::c_void>() != handle.ns_view.as_ptr().cast_const()
        })
}

#[cfg(not(target_os = "macos"))]
pub(crate) fn native_child_has_focus(_: &gpui::Window) -> bool {
    false
}

#[cfg(target_os = "macos")]
fn native_key_repeat() -> bool {
    let Some(mtm) = objc2::MainThreadMarker::new() else {
        return false;
    };
    objc2_app_kit::NSApplication::sharedApplication(mtm)
        .currentEvent()
        .is_some_and(|event| {
            event.r#type() == objc2_app_kit::NSEventType::KeyDown && event.isARepeat()
        })
}

#[cfg(not(target_os = "macos"))]
fn native_key_repeat() -> bool {
    false
}

/// AppKit auto-validation overrides MenuItem.disabled. GPUI's default only
/// checks the action type, so commands sharing InvokeCommand need an ID check.
pub(crate) fn is_menu_action_available(action: &dyn gpui::Action, cx: &mut gpui::App) -> bool {
    if let Some(action) = action.as_any().downcast_ref::<InvokeCommand>() {
        return cx.try_global::<CommandState>().is_some_and(|state| {
            state
                .commands
                .iter()
                .any(|entry| entry.command.id == action.id && entry.command.enabled)
        });
    }
    cx.is_action_available(action)
}

fn restore_menu(menu: gpui::OwnedMenu) -> gpui::Menu {
    gpui::Menu {
        name: menu.name.into(),
        disabled: menu.disabled,
        items: menu
            .items
            .into_iter()
            .map(|item| match item {
                gpui::OwnedMenuItem::Separator => gpui::MenuItem::Separator,
                gpui::OwnedMenuItem::Submenu(menu) => gpui::MenuItem::Submenu(restore_menu(menu)),
                gpui::OwnedMenuItem::SystemMenu(menu) => gpui::MenuItem::SystemMenu(gpui::OsMenu {
                    name: menu.name,
                    menu_type: menu.menu_type,
                }),
                gpui::OwnedMenuItem::Action {
                    name,
                    action,
                    os_action,
                    checked,
                    disabled,
                } => gpui::MenuItem::Action {
                    name: name.into(),
                    action,
                    os_action,
                    checked,
                    disabled,
                },
            })
            .collect(),
    }
}

/// Replace only Solo application bindings. Existing editing/context bindings
/// and menus survive updates and disposal. Validate before any app mutation.
pub(crate) fn replace_application_commands(
    commands: Vec<ParsedApplicationCommand>,
    callback: Option<crate::renderer::EventCallback>,
    cx: &mut gpui::App,
) -> Result<()> {
    let keymap = cx.key_bindings();
    let retained: Vec<_> = keymap
        .borrow()
        .bindings()
        .filter(|binding| !binding.action().as_any().is::<InvokeCommand>())
        .cloned()
        .collect();
    for command in &commands {
        if let Some(key) = &command.shortcut {
            if key.modifiers.platform && key.key == "q"
                || retained
                    .iter()
                    .any(|binding| binding.match_keystrokes(&[key.clone()]).is_some())
            {
                return Err(Error::from_reason(format!(
                    "Application command {:?} shortcut conflicts with a built-in binding",
                    command.command.id
                )));
            }
        }
    }

    // Bindings are prepared using GPUI's fallible parser before replacing state.
    let mut bindings = retained;
    for command in &commands {
        if command.command.enabled && command.command.scope_element_id.is_none() {
            if let Some(shortcut) = command
                .shortcut
                .as_ref()
                .filter(|key| key.modifiers.platform)
            {
                bindings.push(
                    gpui::KeyBinding::load(
                        &shortcut.unparse(),
                        Box::new(InvokeCommand {
                            id: command.command.id.clone(),
                        }),
                        // Menu accelerator metadata only. Solo handles keyboard
                        // events below, where focus and is_held are available.
                        Some(std::rc::Rc::new(
                            gpui::KeyBindingContextPredicate::parse("SoloNativeMenu")
                                .map_err(|e| Error::from_reason(e.to_string()))?,
                        )),
                        false,
                        None,
                        &gpui::DummyKeyboardMapper,
                    )
                    .map_err(|e| Error::from_reason(e.to_string()))?,
                );
            }
        }
    }
    if !cx.has_global::<CommandState>() {
        let base_menus = cx.get_menus().unwrap_or_else(|| {
            vec![gpui::Menu::new("Solo")
                .items([gpui::MenuItem::action("Quit", Quit)])
                .owned()]
        });
        cx.set_global(CommandState {
            commands: Vec::new(),
            callback: None,
            base_menus,
        });
        cx.on_action(|action: &InvokeCommand, cx| {
            let state = cx.global::<CommandState>();
            if state.commands.iter().any(|entry| {
                entry.command.id == action.id
                    && entry.command.enabled
                    && (entry.command.allow_repeat || !native_key_repeat())
            }) {
                crate::renderer::emit_event_full(
                    &state.callback,
                    0,
                    APPLICATION_COMMAND_EVENT,
                    |event| {
                        event.value = Some(action.id.clone());
                    },
                );
            }
        });
        cx.on_action(|_: &Quit, cx| cx.quit());
        bindings.push(gpui::KeyBinding::new("cmd-q", Quit, None));
    }
    let mut menus: Vec<_> = cx
        .global::<CommandState>()
        .base_menus
        .clone()
        .into_iter()
        .map(restore_menu)
        .collect();
    for entry in &commands {
        if let Some(name) = &entry.command.menu {
            let index = menus
                .iter()
                .position(|menu| menu.name.as_ref() == name)
                .unwrap_or_else(|| {
                    menus.push(gpui::Menu::new(name.clone()));
                    menus.len() - 1
                });
            menus[index].items.push(
                gpui::MenuItem::action(
                    entry.command.label.clone(),
                    InvokeCommand {
                        id: entry.command.id.clone(),
                    },
                )
                .disabled(!entry.command.enabled),
            );
        }
    }
    cx.set_global(CommandState {
        commands,
        callback,
        base_menus: cx.global::<CommandState>().base_menus.clone(),
    });
    cx.clear_key_bindings();
    cx.bind_keys(bindings);
    cx.set_menus(menus);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[gpui::test]
    fn replacement_preserves_editing_and_dispatches_only_current_enabled_commands(
        cx: &mut gpui::TestAppContext,
    ) {
        use std::sync::{Arc, Mutex};
        let events = Arc::new(Mutex::new(Vec::new()));
        let output = events.clone();
        let callback: Option<crate::renderer::EventCallback> =
            Some(Arc::new(move |event| output.lock().unwrap().push(event)));
        cx.update(|cx| {
            crate::renderer::init_key_bindings(cx);
            crate::custom_elements::input::init(cx);
            let original_count = cx.key_bindings().borrow().bindings().len();
            for enabled in [true, false, true] {
                let json = format!(r#"[{{"id":"r","label":"Refresh","shortcut":"cmd-r","menu":"Article","enabled":{enabled}}}]"#);
                replace_application_commands(parse_application_commands(&json).unwrap(), callback.clone(), cx).unwrap();
                assert_eq!(is_menu_action_available(&InvokeCommand { id: "r".into() }, cx), enabled);
                assert_eq!(cx.key_bindings().borrow().bindings().len(), original_count + 1 + usize::from(enabled));
                cx.dispatch_action(&InvokeCommand { id: "r".into() });
            }
        });
        cx.run_until_parked();
        // Both enabled invocations fire; the disabled invocation does not.
        let before = events.lock().unwrap().len();
        assert_eq!(before, 2);
        cx.update(|cx| {
            let bad = parse_application_commands(
                r#"[{"id":"copy","label":"Copy","shortcut":"cmd-c","enabled":true}]"#,
            )
            .unwrap();
            assert!(replace_application_commands(bad, callback.clone(), cx).is_err());
            assert_eq!(cx.global::<CommandState>().commands[0].command.id, "r");
            replace_application_commands(Vec::new(), callback, cx).unwrap();
            assert!(!is_menu_action_available(
                &InvokeCommand { id: "r".into() },
                cx
            ));
            assert!(is_menu_action_available(&Quit, cx));
            cx.dispatch_action(&InvokeCommand { id: "r".into() });
        });
        cx.run_until_parked();
        assert_eq!(events.lock().unwrap().len(), before);
    }

    #[test]
    fn rejects_empty_native_labels_and_menu_names() {
        for json in [
            r#"[{"id":"r","label":" ","enabled":true}]"#,
            r#"[{"id":" ","label":"Refresh","enabled":true}]"#,
            r#"[{"id":"r","label":"Refresh","menu":" ","enabled":true}]"#,
        ] {
            assert!(parse_application_commands(json).is_err());
        }
    }

    #[test]
    fn normalizes_gpui_shortcut_aliases_when_checking_collisions() {
        let error = parse_application_commands(
            r#"[
                {"id":"first","label":"First","shortcut":"cmd-r","enabled":true},
                {"id":"second","label":"Second","shortcut":"super-r","enabled":true}
            ]"#,
        )
        .expect_err("cmd and super must represent the same platform shortcut");

        assert!(error.to_string().contains("shortcut"));
        assert!(error.to_string().contains("second"));
    }

    #[test]
    fn accepts_unmodified_and_multiple_modifier_shortcuts() {
        for shortcut in [
            "space",
            "s",
            "h",
            "o",
            "shift-r",
            "cmd-option-p",
            "ctrl-alt-shift-p",
        ] {
            assert!(parse_application_shortcut(shortcut).is_ok(), "{shortcut}");
        }
        let first = parse_application_shortcut("cmd-option-p").unwrap();
        let second = parse_application_shortcut("alt-super-p").unwrap();
        assert_eq!(first, second);
        assert!(parse_application_commands(
            r#"[
          {"id":"a","label":"A","shortcut":"cmd-option-p","enabled":true},
          {"id":"b","label":"B","shortcut":"alt-super-p","enabled":false}
        ]"#
        )
        .is_err());
    }

    #[test]
    fn scopes_require_attached_focus_and_preserve_editors_and_control_activation() {
        let commands = parse_application_commands(
            r#"[
          {"id":"s","label":"Star","shortcut":"s","scopeElementId":2,"enabled":true},
          {"id":"space","label":"Read","shortcut":"space","scopeElementId":2,"enabled":true}
        ]"#,
        )
        .unwrap();
        let mut tree = crate::retained_tree::RetainedTree::new();
        for (id, kind, parent) in [
            (1, "div", None),
            (2, "div", Some(1)),
            (3, "div", Some(2)),
            (4, "input", Some(2)),
            (5, "textarea", Some(2)),
            (6, "webview", Some(2)),
            (7, "div", Some(1)),
            (8, "div", Some(2)),
        ] {
            tree.create_element(id, kind.into());
            tree.elements.get_mut(&id).unwrap().parent = parent;
        }
        tree.root_id = Some(1);
        tree.elements
            .get_mut(&8)
            .unwrap()
            .events
            .insert("click".into());
        for focus in [Some(2), Some(3)] {
            assert!(accepts_focus(&commands[0], focus, &tree));
        }
        for focus in [None, Some(4), Some(5), Some(6), Some(7), Some(99)] {
            assert!(!accepts_focus(&commands[0], focus, &tree));
        }
        assert!(!accepts_focus(&commands[1], Some(8), &tree));
        tree.elements.get_mut(&2).unwrap().parent = None;
        assert!(!accepts_focus(&commands[0], Some(3), &tree));
    }

    #[test]
    fn rejects_reserved_and_multichord_shortcuts() {
        for shortcut in [
            "tab",
            "shift-tab",
            "cmd-r cmd-s",
            "fn-r",
            "cmd",
            "option",
            "shift",
        ] {
            let json = format!(
                r#"[{{"id":"command","label":"Command","shortcut":"{shortcut}","enabled":true}}]"#
            );
            let error = parse_application_commands(&json)
                .expect_err("reserved keys and sequences must be rejected");
            assert!(
                error.to_string().contains("shortcut"),
                "unexpected error for {shortcut:?}: {error}"
            );
        }
    }

    #[test]
    fn rejects_duplicate_ids_before_replacing_the_command_list() {
        let error = parse_application_commands(
            r#"[
                {"id":"same","label":"First","enabled":true},
                {"id":"same","label":"Second","enabled":true}
            ]"#,
        )
        .expect_err("duplicate command ids must be rejected");

        assert!(error.to_string().contains("same"));
    }
}
