/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The main GPUI renderer exposed to Node.js. */
export declare class SoloRenderer {
  constructor(eventCallback?: (((err: Error | null, arg: EventPayload) => any)) | undefined | null)
  /** Initialize GPUI using the native event-loop architecture for this OS. */
  init(options?: WindowOptions | undefined | null): void
  createElement(id: number, elementType: string): void
  /**
   * Destroy an element and all descendants. Returns array of destroyed IDs
   * so JS can clean up event handlers for the entire subtree.
   */
  destroyElement(id: number): Array<number>
  appendChild(parentId: number, childId: number): void
  removeChild(parentId: number, childId: number): void
  insertBefore(parentId: number, childId: number, beforeId: number): void
  setStyle(id: number, styleJson: string): void
  setText(id: number, content: string): void
  setEventListener(id: number, eventType: string, hasHandler: boolean): void
  /** Set the root element (called from appendChildToContainer). */
  setRoot(id: number): void
  /**
   * Set a custom prop on an element (for non-div/text elements like input, editor, diff).
   * Key is the prop name, value is JSON-encoded.
   */
  setCustomProp(id: number, key: string, valueJson: string): void
  /** Get a custom prop value from an element. Returns JSON string or null. */
  getCustomProp(id: number, key: string): string | null
  /** Signal that a batch of mutations is complete. Triggers re-render. */
  commitMutations(): void
  /**
   * Apply a batch of mutations in a single FFI call.
   *
   * Accepts a JSON array of mutation tuples. Each tuple is an array where
   * the first element is the operation name (string) and remaining elements
   * are the arguments:
   *
   *   ["createElement",    id, "type"]
   *   ["destroyElement",   id]
   *   ["appendChild",      parentId, childId]
   *   ["removeChild",      parentId, childId]
   *   ["insertBefore",     parentId, childId, beforeId]
   *   ["setStyle",         id, { ...style } | "{styleJson}"]
   *   ["setText",          id, "content"]
   *   ["setEventListener", id, "eventType", true|false]
   *   ["setRoot",          id]
   *   ["setCustomProp",      id, "key", value | "{valueJson}"]
   *   ["setCustomPropValue", id, "key", value]
   *
   * Returns accumulated destroyed IDs from all destroyElement ops.
   * Acquires the tree mutex ONCE for the entire batch.
   */
  applyBatch(json: string): Array<number>
  /** Pump the native event loop. Returns false after the last window closes. */
  tick(): boolean
  isInitialized(): boolean
  /** Whether JavaScript must drive the native event loop with tick(). */
  requiresTick(): boolean
  getWindowSize(): WindowSize
  /** Replace application commands atomically. macOS only for now. */
  setApplicationCommands(json: string): void
  /**
   * Show the macOS file-open dialog without blocking the JavaScript or UI
   * thread. The returned promise resolves to selected paths, or `null` on
   * cancellation.
   */
  selectFiles(optionsJson: string): Promise<Array<string> | null>
  /**
   * Show the macOS save-destination dialog without blocking the JavaScript
   * or UI thread. The returned promise resolves to a path, or `null` on
   * cancellation. Solo never creates or writes the selected path.
   */
  selectSavePath(optionsJson: string): Promise<string | null>
  /**
   * Replace or remove the macOS system-appearance observer and return the
   * current normalized appearance. The token is echoed in change events so
   * the Solid layer can discard notifications queued for an old owner.
   */
  setSystemAppearanceSubscription(token?: string | undefined | null): string
  /** `"hidden"` | `"minimal"` | `"full"`. Paints into the scene after layout. */
  setDebugFrameOverlay(mode: string): string
  /** Hidden → minimal → full → hidden. */
  cycleDebugFrameOverlay(): string
  getDebugFrameOverlay(): string
  /** Clears the last 1000 draw samples. Frame count stays. */
  resetDebugFrameOverlayStats(): void
  setWindowTitle(title: string): void
  focusElement(elementId: number): void
  blur(): void
  /** The current text selection joined in document order, or null. */
  getSelectedText(): string | null
  /** Drop the current selection and request a repaint. */
  clearSelection(): void
  /**
   * Set the scroll offset of a scrollable element.
   * x and y are negative pixel values (scroll down = more negative y).
   */
  scrollTo(elementId: number, x: number, y: number): void
  /** Scroll a child into view by its index in the children list. */
  scrollToItem(elementId: number, index: number): void
  /**
   * Get the current scroll offset of a scrollable element.
   * Returns [x, y] or null if the element has no scroll handle.
   */
  getScrollOffset(elementId: number): Array<number> | null
  getAutomationTree(): string
  getElementBounds(id: number): Array<number> | null
  getAllText(): Array<string>
  getPaintedText(): Array<string>
  simulateClick(x: number, y: number, button?: number | undefined | null): void
  simulateMouseDown(x: number, y: number, button?: number | undefined | null): void
  simulateMouseUp(x: number, y: number, button?: number | undefined | null): void
  simulateMouseMove(x: number, y: number, pressedButton?: number | undefined | null): void
  simulateScrollWheel(x: number, y: number, deltaX: number, deltaY: number): void
  /**
   * Type a space-separated sequence of keystrokes, e.g. `"a enter cmd-s"`.
   *
   * Text is inserted through GPUI's input pipeline, so it lands in whatever
   * element has focus. That is the point: this is a real key event, not a
   * JS-bound value write, so `onChange` and `onKeyDown` fire as they would
   * for a human. Focus the target first — see `focus_element`.
   */
  simulateKeystrokes(keystrokes: string): void
  /**
   * A key down with no matching key up.
   *
   * Fires `onKeyDown` but does **not** insert text — use
   * [`Self::simulate_keystrokes`] to type. Matches
   * `TestSoloRenderer::simulate_key_down`.
   */
  simulateKeyDown(keystroke: string, isHeld?: boolean | undefined | null): void
  /** A key up, paired with [`Self::simulate_key_down`]. */
  simulateKeyUp(keystroke: string): void
  clockPause(): number
  clockSet(nowMs: number): number
  clockFastForward(deltaMs: number): number
  clockResume(): number
  captureScreenshot(path: string): void
}

export interface EventModifiers {
  shift: boolean
  ctrl: boolean
  alt: boolean
  cmd: boolean
}

/** Event payload sent back to JS when a user interacts with an element. */
export interface EventPayload {
  /** Numeric element ID (matches the ID assigned in JS via createElement). */
  elementId: number
  /**
   * Event type string — matches the key used in EVENT_PROPS on the JS side.
   * e.g. "click", "mouseDown", "mouseEnter", "keyDown", "scroll", etc.
   */
  eventType: string
  /** Mouse X position in window coordinates (pixels). */
  x?: number
  /** Mouse Y position in window coordinates (pixels). */
  y?: number
  /**
   * Which mouse button: 0=left, 1=middle, 2=right.
   * Populated for: mouseDown, mouseUp, click, mouseDownOutside, contextMenu.
   */
  button?: number
  /**
   * Number of consecutive clicks (1=single, 2=double, 3=triple).
   * Populated for: mouseDown, mouseUp, click.
   */
  clickCount?: number
  /**
   * Whether this is a right-click (convenience for click events).
   * true when button==2 or ClickEvent::is_right_click().
   */
  isRightClick?: boolean
  /**
   * Which mouse button is currently held during a mouseMove.
   * Same encoding as `button`: 0=left, 1=middle, 2=right.
   * Populated for: mouseMove.
   */
  pressedButton?: number
  /**
   * Key name, e.g. "a", "enter", "escape", "down", "left", "f1".
   * Populated for: keyDown, keyUp.
   */
  key?: string
  /**
   * The character produced by the key press (e.g. "ß" for option-s).
   * May differ from `key` when modifiers are active.
   * Populated for: keyDown, keyUp.
   */
  keyChar?: string
  /**
   * Whether this is a key-repeat event (key held down).
   * Populated for: keyDown.
   */
  isHeld?: boolean
  /**
   * Scroll delta on the X axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaX?: number
  /**
   * Scroll delta on the Y axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaY?: number
  /**
   * true = pixel-precise (trackpad), false = line-based (mouse wheel).
   * Populated for: scroll.
   */
  precise?: boolean
  /**
   * Touch phase for scroll: "started", "moved", "ended".
   * Populated for: scroll (trackpad gestures).
   */
  touchPhase?: string
  /**
   * true = mouse entered element, false = mouse left element.
   * Populated for: mouseEnter, mouseLeave.
   */
  hovered?: boolean
  /**
   * Element-defined string payload.
   * Populated for: `<diff>` toggleFile (the file path), showMore (the
   * hidden line count), and lineClick (the line text); `<markdown>`
   * linkClick (the URL).
   */
  value?: string
  /** Line number on the pre-change side. Populated for: `<diff>` lineClick. */
  oldLine?: number
  /** Line number on the post-change side. Populated for: `<diff>` lineClick. */
  newLine?: number
  modifiers?: EventModifiers
}

/**
 * Ask macOS to open an absolute HTTP/HTTPS URL in its default browser.
 * Success means the OS accepted the request, not that the page loaded.
 */
export declare function openExternalUrl(url: string): void

export interface WindowOptions {
  title?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  resizable?: boolean
  fullscreen?: boolean
  /** Plain alpha transparency. Prefer `window_background` when you need blur. */
  transparent?: boolean
  /** Hide the native titlebar so the app can draw chrome under the traffic lights. */
  titlebarTransparent?: boolean
  /**
   * `"opaque"` | `"transparent"` | `"blurred"`. `transparent: true` is the
   * same as `"transparent"` when this is unset.
   */
  windowBackground?: string
  trafficLightX?: number
  trafficLightY?: number
}

export interface WindowSize {
  width: number
  height: number
}

/** Replace the system clipboard with plain Unicode text. macOS only. */
export declare function writeClipboardText(text: string): void
